
#Screen constants
WIDTH_SCREEN, HEIGHT_SCREEN = 600, 600

#Player constants
X_COR_PLAYER2 = (WIDTH_SCREEN / 2 ) - 100
X_COR_PLAYER1 = X_COR_PLAYER2 * -1

#Scoreboard position constants
X_COR_SCOREBOARD2 = 100
X_COR_SCOREBOARD1 = X_COR_SCOREBOARD2 * -1
Y_COR_SCOREBOARD12 = (HEIGHT_SCREEN / 2) - 100

#Limits to score constants
VERTICAL_lEFT_LIMIT_TO_SCORE = (-1 * (WIDTH_SCREEN / 2)) + 10
VERTICAL_RIGHT_LIMIT_TO_SCORE = (WIDTH_SCREEN / 2) - 10

#Game constants
SCORE_TO_WIN = 10